exec: |
  bash -c '
  while ! nc -z $FIRST_SERVER_IP 4647 </dev/null; do sleep 1; done
  mkdir /etc/nomad.d && cat > /etc/nomad.d/nomad.hcl << EOF
  data_dir  = "/opt/nomad/data"
  datacenter = "dc1"

  client {
    enabled          = true
    servers = ["$FIRST_SERVER_IP"]
  }
  EOF
  '
oneshot: true