exec: |
  bash -c '
  mkdir /etc/nomad.d && cat > /etc/nomad.d/nomad.hcl << EOF
  data_dir  = "/opt/nomad/data"
  datacenter = "dc1"

  server {
    enabled          = true
    bootstrap_expect = ${NOMAD_SERVERS:-1}
  }
  EOF
  '
oneshot: true